os: linux

language: php

services: mysql

notifications:
  email:
    on_success: never
    on_failure: change

# PHP v5.x isn't supported in the default build environment
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

jobs:
  include:
    # Canary for our oldest-supported version
    - name: Legacy
      # PHP v5.6 is the oldest version Wordpress supports
      php: 5.6
      env: WP_VERSION=4.4 WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer global require "phpunit/phpunit=6.5.*"
    elif [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=7.5.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
  - composer install --no-interaction
  - nvm install --lts
  - nvm use --lts
  - npm install -g yarn
  - npm install -g webpack
  - yarn install

script:
  - ./vendor/bin/phpcs -s --standard=phpcs.ruleset.xml
  - phpunit
  - yarn run build
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script: sh bin/deploy.sh
  on:
    branch: master
    php: 7.0
