os: linux

language: php

services: mysql

notifications:
  email:
    on_success: never
    on_failure: change

# PHP v5.x isn't supported in the default build environment
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.3

env:
  - WP_VERSION=latest

jobs:
  include:
    # Canary for our oldest-supported version
    # PHP v5.6 is the oldest version Wordpress supports
    - php: 5.6
      env: WP_VERSION=4.4

# Enable dependency caching
cache:
  apt: true
  directories:
    - vendor
    - $HOME/.npm
    - $HOME/.composer/cache

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
      composer global require "phpunit/phpunit=4.8.*"
    elif [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer global require "phpunit/phpunit=6.5.*"
    else
      composer global require "phpunit/phpunit=7.*"
    fi
  - |
  - composer install --no-interaction
  - nvm install --lts
  - nvm use --lts
  - npm install -g yarn
  - npm install -g webpack
  - yarn install

script:
  - ./vendor/bin/phpcs -s --standard=phpcs.ruleset.xml
  - bash bin/test.sh
  - yarn run build
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script: sh bin/deploy.sh
  on:
    branch: master
    php: 7.0
